---
stages:
  - build

variables:
    GIT_SUBMODULE_STRATEGY: normal
    GIT_STRATEGY: clone


build:
  stage: build
  tags:
    - flipper_firmware
  script:
    - docker-compose up -d
    - docker-compose exec -T dev make
  artifacts:
    paths:
      - dist/
